import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Posts from "@/components/Posts";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    const getUsers = async () => {
      try {
        const email = "CUcurucu";
        const password = "mucupucu";
        const response = await fetch(
          "http://localhost/next-php-blog/server/auth",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ email, password }),
          }
        );

        const data = await response.json();

        if (response.ok) {
          console.log(data.message); // User created successfully
        } else {
          console.log("Failed to create user:", data.message);
        }
      } catch (error) {
        console.error("Error:", error);
      }
    };

    getUsers();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Posts />
    </>
  );
}
